#pragma once

namespace TCPIP
{
    enum class RequestType : char {CLIENT_CONNECTED, CLIENT_DISCONNECTED, RECEIVING_REQUEST, REQUEST_RECEIVED, FILE_INFO_RECEIVED, FILE_CHUNK_RECEIVED, REQUEST_OK, REQUEST_TRY_AGAIN, REQUEST_ERROR};
}