name: Documentation

on:
  push:
    tags:
      - "*"
    branches: [ main, master ]

jobs:
  build:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2

    - name: gcc/g++
      run: |
        sudo apt-get install gcc-13
        sudo apt-get install g++-13
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 130 --slave /usr/bin/g++ g++ /usr/bin/g++-13  
    
    - name: Install Conan
      id: conan
      uses: turtlebrowser/get-conan@main
    
    - name: Detect profile
      run: conan profile detect
    
    - name: Install Doxygen
      run: |
        sudo apt-get install doxygen
        pip install jinja2 Pygments
    - name: configure
      run: |
        conan install . --output-folder=bin --profile=debugprofile.txt --profile:b=debugprofile.txt --build=missing
        cmake . -B bin -DCMAKE_BUILD_TYPE=Debug --preset conan-debug
    - name: docs building
      run: |
        cd docs
        doxygen
    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        build_dir: ./docs/html
